<?php

/*
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * @copyright    XOOPS Project https://xoops.org/
 * @license      GNU GPL 2 or later (http://www.gnu.org/licenses/gpl-2.0.html)
 * @package
 * @since
 * @author       Kaotik (kaotik1@gmail.com), GigaPHP, XOOPS Development Team
 */
$moduleDirName = basename(__DIR__);

$modversion['version']       = '2.01';
$modversion['release_date']  = '2020/01/27';
$modversion['module_status'] = 'Beta 1';
$modversion['name']          = _MI_GROUPS_NAME;
$modversion['description']   = _MI_GROUPS_DESC;
$modversion['author']        = 'Kaotik, GigaPHP, Mamba';
$modversion['credits']       = 'XOOPS Module Development Team';
$modversion['license']       = 'GPL see LICENSE';
$modversion['official']      = 0;
$modversion['image']         = 'assets/images/logoModule.png';
$modversion['dirname']       = $moduleDirName;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = "groups_categories";
//----------------------*/

//Has Main Menu
$modversion['hasMain'] = 0;

// Admin things
$modversion['hasAdmin']    = 1;
$modversion['system_menu'] = 1;
$modversion['adminindex']  = 'admin/index.php';
$modversion['adminmenu']   = 'admin/menu.php';

// ------------------- Help files ------------------- //
$modversion['help']        = 'page=help';
$modversion['helpsection'] = [
    ['name' => _MI_GROUPS_OVERVIEW, 'link' => 'page=help'],
    ['name' => _MI_GROUPS_DISCLAIMER, 'link' => 'page=disclaimer'],
    ['name' => _MI_GROUPS_LICENSE, 'link' => 'page=license'],
    ['name' => _MI_GROUPS_SUPPORT, 'link' => 'page=support'],
];

//////////////////////////////////////////////////////////////////
// Templates
$modversion['templates'][1]['file']        = 'gm_admin_navbar.tpl';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file']        = 'gm_main.tpl';
$modversion['templates'][2]['description'] = '';

/* Blocks
$modversion['blocks'][1]['file'] = "shopping_cart.php";
$modversion['blocks'][1]['name'] = 'Kshop Shopping Cart';
$modversion['blocks'][1]['description'] = 'Displays the shopping cart as a block';
$modversion['blocks'][1]['show_func'] = "shopping_cart";
$modversion['blocks'][1]['template'] = 'shopping_cart.html';
//----------------------*/

/* Config categories
$modversion['configcat'][1]['nameid'] = 'settings';
$modversion['configcat'][1]['name'] = '_KSHOP_CAT_SETTINGS';
$modversion['configcat'][1]['description'] = '_KSHOP_CAT_SETTINGS_DSC';
//----------------------*/

/*Preferences
$i=1;
$modversion['config'][$i]['name'] = 'debug';
$modversion['config'][$i]['title'] = '_KS_DEBUG';
$modversion['config'][$i]['description'] = '_KS_DEBUGDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$modversion['config'][$i]['category'] = 'settings';
$i++;
//----------------------*/
