<?php

/*
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * @copyright    XOOPS Project (https://xoops.org)
 * @license      GNU GPL 2 or later (https://www.gnu.org/licenses/gpl-2.0.html)
 * @author       Kaotik (kaotik1@gmail.com), GigaPHP, XOOPS Development Team
 */
$moduleDirName = basename(__DIR__);
$moduleDirNameUpper = mb_strtoupper($moduleDirName);

$modversion['version']       = '2.01';
$modversion['release_date']  = '2020/01/27';
$modversion['module_status'] = 'Beta 1';
$modversion['name']          = _MI_GROUPS_NAME;
$modversion['description']   = _MI_GROUPS_DESC;
$modversion['author']        = 'Kaotik, GigaPHP, Mamba';
$modversion['credits']       = 'XOOPS Module Development Team';
$modversion['license']       = 'GPL see LICENSE';
$modversion['official']      = 0;
$modversion['image']         = 'assets/images/logoModule.png';
$modversion['dirname']       = $moduleDirName;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = "groups_categories";
//----------------------*/

//Has Main Menu
$modversion['hasMain'] = 0;

// Admin things
$modversion['hasAdmin']    = 1;
$modversion['system_menu'] = 1;
$modversion['adminindex']  = 'admin/index.php';
$modversion['adminmenu']   = 'admin/menu.php';

// ------------------- Help files ------------------- //
$modversion['help']        = 'page=help';
$modversion['helpsection'] = [
    ['name' => _MI_GROUPS_OVERVIEW, 'link' => 'page=help'],
    ['name' => _MI_GROUPS_DISCLAIMER, 'link' => 'page=disclaimer'],
    ['name' => _MI_GROUPS_LICENSE, 'link' => 'page=license'],
    ['name' => _MI_GROUPS_SUPPORT, 'link' => 'page=support'],
];

//////////////////////////////////////////////////////////////////
// ------------------- Templates ------------------- //
$modversion['templates'] = [
    ['file' => 'gm_admin_navbar.tpl', 'description' => ''],
    ['file' => 'gm_main.tpl', 'description' => ''],
];

/* Blocks
$modversion['blocks'][] = [
    'file' =>  "shopping_cart.php",
    'name' =>  'Kshop Shopping Cart',
    'description' =>  'Displays the shopping cart as a block',
    'show_func' =>  "shopping_cart",
    'template' =>  'shopping_cart.html',
];
//----------------------
*/

/* Config categories
$modversion['configcat'][1]['nameid'] = 'settings';
$modversion['configcat'][1]['name'] = '_KSHOP_CAT_SETTINGS';
$modversion['configcat'][1]['description'] = '_KSHOP_CAT_SETTINGS_DSC';
//----------------------*/

/*Preferences
    $modversion['config'][] = [
    'name' =>  'debug',
    'title' =>  '_KS_DEBUG',
    'description' =>  '_KS_DEBUGDSC',
    'formtype' =>  'yesno',
    'valuetype' =>  'int',
    'default' =>  0,
    'category' =>  'settings',
];
//----------------------*/

/**
 * Make Sample button visible?
 */
$modversion['config'][] = [
    'name'        => 'displaySampleButton',
    'title'       => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_SAMPLE_BUTTON',
    'description' => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_SAMPLE_BUTTON_DESC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => 1,
];

/**
 * Show Developer Tools?
 */
$modversion['config'][] = [
    'name'        => 'displayDeveloperTools',
    'title'       => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_DEV_TOOLS',
    'description' => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_DEV_TOOLS_DESC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => 0,
];
