<?php
// +--------------------------------------------------------------------------+
// |							Group Manager
// | 							Module for Xoops
// |            				www.kaotik.biz
// |            				kaotik1@gmail.com
// +--------------------------------------------------------------------------+

$modversion['name'] = _MI_GROUPS_NAME;
$modversion['version'] = 1.02;
$modversion['description'] = _MI_GROUPS_DESC;
$modversion['author'] = "kaotik, GibaPhp";
$modversion['help']        = 'page=help';
$modversion['license']     = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['official'] = 0;
$modversion['image'] = "images/gm_logo.png";
$modversion['dirname'] = "groups";

$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16'] = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = '../../Frameworks/moduleclasses/icons/32';

//about
$modversion["module_website_url"] = "http://www.xoops.org/";
$modversion["module_website_name"] = "XOOPS";
$modversion["release_date"] = "2012/03/21";
$modversion["module_status"] = "RC";
$modversion["author_website_url"] = "http://www.xoops.org/";
$modversion["author_website_name"] = "XOOPS";
$modversion['min_php']='5.2';
$modversion['min_xoops']='2.5';
$modversion['min_admin']='1.1';
$modversion['min_db']= array('mysql'=>'5.0.7', 'mysqli'=>'5.0.7');

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = "groups_categories";
//----------------------*/

//Has Main Menu
$modversion['hasMain'] = 0;


// Admin things
$modversion['hasAdmin'] = 1;
$modversion['system_menu'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";



//////////////////////////////////////////////////////////////////
// Templates
$modversion['templates'][1]['file'] = 'gm_admin_navbar.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'gm_main.html';
$modversion['templates'][2]['description'] = '';


/* Blocks
$modversion['blocks'][1]['file'] = "shopping_cart.php";
$modversion['blocks'][1]['name'] = 'Kshop Shopping Cart';
$modversion['blocks'][1]['description'] = 'Displays the shopping cart as a block';
$modversion['blocks'][1]['show_func'] = "shopping_cart";
$modversion['blocks'][1]['template'] = 'shopping_cart.html';
//----------------------*/



/* Config categories
$modversion['configcat'][1]['nameid'] = 'settings';
$modversion['configcat'][1]['name'] = '_KSHOP_CAT_SETTINGS';
$modversion['configcat'][1]['description'] = '_KSHOP_CAT_SETTINGS_DSC';
//----------------------*/




/*Preferences
$i=1;
$modversion['config'][$i]['name'] = 'debug';
$modversion['config'][$i]['title'] = '_KS_DEBUG';
$modversion['config'][$i]['description'] = '_KS_DEBUGDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$modversion['config'][$i]['category'] = 'settings';
$i++;
//----------------------*/

?>